### ISSUE TITLE
Change drawText() function

### ISSUE THREAD

**Issue by MajicDesigns** [MajicDesigns/MD_MAXPanel#3]
Issue raised on Arduino++ blog

> Can You change the third parameter of drawText from "char *psz" to "const char *psz".
> So it will be easier to pass strings...

**Comment by MajicDesigns** [comment]
Please explain the issue that this solution is trying to solve.

**Comment by AndreasPercher** [comment]
Using _const char *psz_  instead of _char *psz_ allows to send constants and (String).c_str() easyly.

**Comment by MajicDesigns** [comment]
Not sure I follow the logic. A pointer to the string is the same no matter what. The const restricts the pointer to not changing in the function. I don't understand how making the parameter cont makes sending this parameter 'easier'. Can you provide an example where it is hard and how the change makes this easy.

**Comment by AndreasPercher** [comment]
This did not compile with Lolin/Wemos as target;
Sting text = "print me";
mp.drawText(x,,text.c_str());

**Comment by MajicDesigns** [comment]
But this does
`  mp.drawText(0, 0, (char *)text.c_str(), MD_MAXPanel::ROT_0);`

**Comment by AndreasPercher** [comment]
Yes, but I think **char*** implies that the data will/can be changed inside the function.
According to 
https://stackoverflow.com/questions/4949254/const-char-const-versus-const-char
the "correct" syntax "should" be   const char* const ...

OK, it's your Module, so I shut up and use **char***   ;-)
Once again : great job

**Comment by MajicDesigns** [comment]
Fair enough. I don't understand why people bother using String in microcontrollers, so that makes us even :-)

**Comment by AndreasPercher** [comment]
On last addemdum:
https://lefticus.gitbooks.io/cpp-best-practices/content/04-Considering_Safety.html
