### ISSUE TITLE
Inverted text instead of blank text on drawText(... state=false)

### ISSUE THREAD

**Issue by AndreasPercher** [MajicDesigns/MD_MAXPanel#4]
I don't understand the purpose of  **state=false** in drawText - in my small world there is no need  for black chars on black backround  ;-)
But I "need" (want have)  inverted text.
So I think it can be a good idea to change the  **... ? state : false** in draw text to  **... ? state : !state** to get inverted text. 

PS What about a state paramter in the **clear** functions? (or a **drawFilledRect**-Function)

**Comment by MajicDesigns** [comment]
Black chars on black background erases the text that was there. This is used all the time in the examples to update the score without erasing the entire area.

If you need inverted text, then invert the background by setting the background on (series of lines) and then drawing the text 'off'. The problem with implementing reverse text is how big to make the reverse area - same height as the text? 1 pixel bigger? 2? 3? The answer will depend on the application, so the most flexible is to let the program deal with this and make sure that the text can be drawn 'in reverse', which is what  was done.

state for clear() could work to reverse the whole display makes sense. However this will make the call less efficient as it does not directly translate to a MD_MAX72xx function. I will put this on the list of things to add in.

draw<Polygon>Fill (<polygon>= rect, circle, triangle, quadrilateral) could make sense. If you implement this please let me know and we can include it in the permanent library.

**Comment by AndreasPercher** [comment]
OK, I only "implemented" (aka copied) the partial clear/drawFillRectangle:
  ```
inline void clear(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, bool state = true)
     { for (uint8_t i=x1; i<=x2; i++) drawVLine(i, y1, y2, !state); };  // inverted state
```
and 
```
  inline void drawFillRectangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, 
      bool state = true)
     { for (uint8_t i=x1; i<=x2; i++) drawVLine(i, y1, y2, state); };
```

The other thing is the inverted text.

The way you mentioned was my first attempt because this is the way the documentation implies it.
But in this case, you will get black text on black background because of:
`setPoint(x + i, y - j, (buf[i] & (1 << j) ? state : false));`
which should than be 
```
if ( (buf[i] & (1 << j)) {
  setPoint(x + i, y - j, state);
}
```
But in this case you have to clear the background all the time.

What about a sixth parameter eg **bgState** which defaults to **false** with 
```
false = make all background pixel black
true  = invert all background pixel
```
so it can be
```
uint16_t MD_MAXPanel::drawText(uint16_t x, uint16_t y, char *psz, rotation_t rot,
    bool state, bool bgState ) {
...
      setPoint(x + i, y - j, (buf[i] & (1 << j) ? state : bgState && !state ));
...
```

**Comment by MajicDesigns** [comment]
I think the clear() should use the 'state' variable as passed through (ie, not !state). State should default to false so that no parameter is what most people would expect (ie, clear to 'off' state) and it continues current functionality for existing code. If you want to clear to reverse state then specify 'true' to get what you want (ie, true should be the indicator for ON to be consistent everywhere).

As for drawText(), the original code 
`setPoint(x + i, y - j, (buf[i] & (1 << j) ? state : false));`
was done to clear anything on the background of the text, to avoid having to call clear() for the area around the text. If you want to preserve the background (as in the case of reverse) then your mod should be correct.

> What about a sixth parameter eg bgState

Not really keen on this. Would prefer to just leave the background on and force the application to take care of this, especially now that clear() has been changed to add in reverse.

> drawFillRectangle

What about drawFillTriangle() and drawFillCircle()?

**Comment by AndreasPercher** [comment]
> Would prefer to just leave the background on and force the application to take care of this, especially now that clear() has been changed to add in reverse.


That will be OK for me, because this is the documented behavior.

> What about drawFillTriangle() and drawFillCircle()?


I haven't need them yet, but I think drawFillCircle is easyly this
```
bool MD_MAXPanel::drawCircleLines(uint16_t xc, uint16_t yc, uint16_t x, uint16_t y, bool state)
// draw symmetrical circle lines
{
  bool b = true;
  b &= drawHLine(yc - y, xc - x, xc + x,state);
  b &= drawHLine(yc + y, xc - x, xc + x,state);
  b &= drawHLine(yc - x, xc - y, xc + y,state);
  b &= drawHLine(yc + x, xc - y, xc + y,state);
  return(b);
}

bool MD_MAXPanel::drawFillCircle(uint16_t xc, uint16_t yc, uint16_t r, bool state /* = true */ )
// draw a circle given center and radius
// Bresenhams Algorith from http://www.pracspedia.com/CG/bresenhamcircle.html
{
  int x = 0, y = r;
  int pk = 3 - (2 * r);
  bool b = false;
  _D->control(MD_MAX72XX::UPDATE, MD_MAX72XX::OFF);
  PRINT("\n\nCircle center ", xc); PRINT(",", yc); PRINT(" radius ", r);
  b &= drawCircleLines(xc, yc, x, y, state);
  while (x < y)
  {
    // check for decision parameter and correspondingly update pk, x, y
    if (pk <= 0)
    {
      pk = pk + (4 * x) + 6;
      b &= drawCircleLines(xc, yc, ++x, y, state);
    }
    else
    {
      pk = pk + (4 * (x - y)) + 10;
      b &= drawCircleLines(xc, yc, ++x, --y, state);
    }
  }
  update(_updateEnabled);
  return(b);
}
```

**Comment by AndreasPercher** [comment]
Not very well tested, but seems to work:
```
bool MD_MAXPanel::drawFillTriangle(uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t x3, uint16_t y3, bool state /* = true */ )
// draw an arbitrary filled triangle given the 3 corner vertices
{
  bool b = true;
  _D->control(MD_MAX72XX::UPDATE, MD_MAX72XX::OFF);
  // find line with longest y-component and sort it on the first position
  if (y1>y3) {
    uint16_t y = y1;y1 = y3; y3 = y;
    uint16_t x = x1;x1 = x3; x3 = x;
  }
  if (y1>y2) {
    uint16_t y = y1;y1 = y2; y2 = y;
    uint16_t x = x1;x1 = x2; x2 = x;
  }
  if (y2<y3) {
    uint16_t y = y2;y2 = y3; y3 = y;
    uint16_t x = x2;x2 = x3; x3 = x;
  }
  // draw the rect as h-lines
  for (uint16_t ya=y1;ya<=y2;ya++) {
    uint16_t  xa = x1 + (2 * (ya-y1) * (x2-x1)) / (2*(y2-y1)); // rounding
    uint16_t  xb =0;
    if (ya<=y3) {
      xb =  x1 + (2 *(ya-y1) * (x3-x1)) / (2*(y3-y1)); // rounding
    } else {
      xb =  x3 + (2 *(ya-y3) * (x2-x3)) / (2*(y2-y3)); // rounding
    }
    b &= drawHLine(ya,xa,xb,state);
  }
  update(_updateEnabled);
  return(b);
}
```

**Comment by MajicDesigns** [comment]
Included in next release of the library
