### ISSUE TITLE
ROT_90; not working (or I don't know how to use it)

### ISSUE THREAD

**Issue by joveaaron** [MajicDesigns/MD_MAXPanel#6]
Hello. I wanted to use the TETRIS Demo game that is built into the MD_MAXPanel library. But I wanted to use it vertically. (as my MAX72xx is a 4 in 1) I sat the values for X devices and Y devices and it wasn't working as supposed. I tried to use the `ROT_90;` that is stated in the MD_MAXPanel.h file but I had no luck left. So... If anyone can help me please let me know.

All answers appreciated.

EDIT: I figured out how to do it but it just rotates all screens. I managed to get it better as my screen is FC16 so I tried ICSTATION with ROT_90 and it worked! Partially. The part of the screen that would be on the bottom is on the top (???) so... I'm screwed.
_________________________________
_Sorry if my English isn't very good. English is my secondary language._

**Comment by MajicDesigns** [comment]
Is a "4 in 1" matrix 8 pixels by 32 pixels (LEDs)? In this case I don't think the game will run properly as it needs more room (display area).

I don't understand this: "it just rotates all screens" - do you mean that each matrix (8x8 LED) is rotated individually?

You need to get the type of matrix properly configured. Use the MD_MAX72xx_Dynamic _HW example - the message you can read is your matrix type. Remember that the data IN is oriented do that it is on the right hand side of the display
