### ISSUE TITLE
Redeclaration of default parameters causes failure to build

### ISSUE THREAD

**Issue by jasonmhite** [MajicDesigns/MD_MAXPanel#7]
On recent versions of the Arduino IDE this library fails to build because of redeclaration of the default parameters from the function prototype in the implementation in `MD_MAXPanel.cpp`.

The solution is pretty simple, just change all of the `bool state = true` to `bool state` in `MD_MAXPanel.cpp` (but leave them alone in the header).

**Comment by MajicDesigns** [comment]
Wrong default branch was set on github (master instead of main). This should now be fixed.

**Comment by jasonmhite** [comment]
Fixed. Thanks for your work on these libraries!
