### ISSUE TITLE
Typo in Headerfile: 'MD_MAX72XXX' has not been declared

### ISSUE THREAD

**Issue by m5k5** [MajicDesigns/MD_MAXPanel#8]
## IMPORTANT
Before submitting this issue
[x] Have you tried using the latest version of the library?
[x] Have you checked this has not already been submitted and/or resolved?

## Subject of the issue
When using the latest version, there will be a compile error due to a typo (there are three Xs instead of two).
See here https://github.com/MajicDesigns/MD_MAXPanel/blob/fc063f11e71db134c01a8e5cf5897f916adada7c/src/MD_MAXPanel.h#L214

## Your Environment
**Library Version: 1.3.1

## Steps to Reproduce
All the files using #include <MD_MAXPanel.h> will run into that error.

**Comment by MajicDesigns** [comment]
Fixed and released as v1.3.2
