### ISSUE TITLE
error: expected constructor (MD_MAXPanel.cpp:54)

### ISSUE THREAD

**Issue by marcoaltomonte** [MajicDesigns/MD_MAXPanel#9]
While compiling a project in Arduino IDE 2.0.3 for an Esp 32 I got this error:
MD_MAXPanel.cpp:54:25: error: expected constructor, destructor, or type conversion before '(' token MD_MAXPanel::MD_MAXPanel(MD_MAX72XXX::moduleType_t mod, SPIClass &spi, uint8_t csPin, uint8_t xDevices, uint8_t yDevices)

Maybe the problem is just a typo in type MD_MAX72XXX: shouldn't that be MD_MAX72XX (just 2 X, not 3)?

**Comment by MajicDesigns** [comment]
This is a repeat of issue #8 which has been fixed. Have you downloaded the latest version of the library?

**Comment by marcoaltomonte** [comment]
Yes: I am using version 1.3.2 (throught the IDE). While the header file has been fixed, cpp still has the definition with a typo with 3 Xs

**Comment by MajicDesigns** [comment]
Ok, should be correct now. Same version number.
